# Generated by Django 6.0.8 on 2026-08-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleregistry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_registrations', to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource', 'resource_id'], name='organizatio_resourc_10a599_idx'),
        ),
        migrations.AddConstraint(
            model_name='moduleregistry',
            constraint=models.UniqueConstraint(fields=('organization', 'module_key'), name='unique_module_per_organization'),
        ),
    ]
