# Generated by Django 6.0.8 on 2026-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='license_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
