# Generated by Django 6.0.8 on 2026-08-20 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_organizations(apps, schema_editor):
    """Hospitals that pre-date the review gate were created when registration
    granted access immediately — approve them so their owners keep working.
    Only registrations made after this migration start as pending.
    """
    Organization = apps.get_model("organization", "Organization")
    Organization.objects.update(status="approved")


def revert_grandfather(apps, schema_editor):
    """No-op: status is dropped when this migration is reversed."""


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_add_license_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='license_authority',
            field=models.CharField(blank=True, choices=[('phc', 'Punjab Healthcare Commission (PHC)'), ('shcc', 'Sindh Healthcare Commission (SHCC)'), ('kphcc', 'KP Healthcare Commission'), ('bhcc', 'Balochistan Healthcare Commission'), ('ihra', 'Islamabad Healthcare Regulatory Authority (IHRA)'), ('ajk_gb', 'AJK / Gilgit-Baltistan health department'), ('other', 'Other / not listed')], help_text='Which regulator issued the licence — tells the reviewer whose register to search.', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='license_document',
            field=models.FileField(blank=True, help_text='Scan of the licence certificate, for the reviewer to inspect.', null=True, upload_to='licenses/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='review_note',
            field=models.TextField(blank=True, help_text='What the reviewer actually checked — registry consulted, date, callback outcome.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(grandfather_existing_organizations, revert_grandfather),
    ]
