# Generated by Django 6.0.8 on 2026-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_care_team_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='building_photo',
            field=models.FileField(blank=True, help_text='A photo of the hospital or office building, shown on its profile.', null=True, upload_to='organizations/%Y/%m/'),
        ),
    ]
