# Generated by Django 6.0.8 on 2026-09-05 07:45

import momcare_platform.core.common.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organization_building_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='building_photo',
            field=models.FileField(blank=True, help_text='A photo of the hospital or office building, shown on its profile.', null=True, storage=momcare_platform.core.common.storage.DatabaseStorage(), upload_to='organizations/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='license_document',
            field=models.FileField(blank=True, help_text='Scan of the licence certificate, for the reviewer to inspect.', null=True, storage=momcare_platform.core.common.storage.DatabaseStorage(), upload_to='licenses/%Y/%m/'),
        ),
    ]
