# Generated by Django 6.0.8 on 2026-09-06 09:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_migrate_files_to_database_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='confidence_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Model confidence below which an assessment is flagged for a doctor. Leave empty to follow the platform default.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('1.000'))]),
        ),
    ]
