# Generated by Django 6.0.8 on 2026-09-13 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0011_organization_confidence_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="building_photo",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="license_authority",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="license_document",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="license_no",
        ),
    ]
