# Generated by Django 6.0.8 on 2026-09-14 17:56

import momcare_platform.core.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0014_deactivation_request_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="license_image",
            field=models.FileField(
                blank=True,
                null=True,
                storage=momcare_platform.core.common.storage.DatabaseStorage(),
                upload_to="organization/licenses/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="license_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
