# Generated by Django 6.0.8 on 2026-09-23 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_clinical_notes_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('patient_join_request', 'Patient join request')], db_index=True, max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_read', '-created_at'], name='organizatio_organiz_f6910f_idx')],
            },
        ),
    ]
