# Generated by Django 6.0.8 on 2026-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_analytics_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_custom_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
