# Generated by Django 6.0.8 on 2026-09-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_ai_instruction_preset_row_level_security'),
        ('ai', '0004_migrate_instructions_to_presets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='ai_custom_instructions',
        ),
    ]
