# Generated by Django 6.0.8 on 2026-09-27 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0017_patient_analytics_caches'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_model', models.CharField(help_text="An OpenRouter model id, e.g. 'google/gemini-2.0-flash-001'.", max_length=200)),
                ('max_words', models.PositiveIntegerField(default=150)),
                ('custom_instructions', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField()),
                ('model_used', models.CharField(max_length=200)),
                ('risk_level_at_generation', models.CharField(blank=True, max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
