# Generated by Django 6.0.8 on 2026-09-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='singleton_id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
    ]
