# Generated by Django 6.0.8 on 2026-09-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_migrate_instructions_to_presets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiproviderconfig',
            name='custom_instructions',
        ),
    ]
