# Generated by Django 6.0.8 on 2026-09-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aisummarytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummarytemplate',
            name='extra_instructions',
            field=models.TextField(blank=True),
        ),
    ]
