# Generated by Django 6.0.8 on 2026-09-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_delete_aiinstructionpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='citations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
