# Generated by Django 6.0.8 on 2026-09-26 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0017_patient_analytics_caches'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.DateField()),
                ('monitoring_seconds', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_periods', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Analytics',
                'verbose_name_plural': 'Patient Analytics',
                'indexes': [models.Index(fields=['patient', 'period_month'], name='analytics_p_patient_6369bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'period_month'), name='unique_patient_period')],
            },
        ),
    ]
