# Generated by Django 6.0.8 on 2026-09-05 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_vitalreading_wide_format'),
        ('patients', '0006_careteammembership_ended_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='riskassessment',
            name='monitoring__level_e55b6a_idx',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='confirmed_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='doctor_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='previous_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=20),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk_level', '-assessed_at'], name='monitoring__risk_le_c2c6f7_idx'),
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='previous_level',
        ),
    ]
