# Generated by Django 6.0.8 on 2026-09-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_risk_level_no_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='monitoring.vitalreading'),
        ),
    ]
