# Generated by Django 6.0.8 on 2026-09-05 22:35

from django.db import migrations, models


def _copy_risk_level_to_final(apps, schema_editor):
    """Existing rows got final_risk_level='low' from the AddField default,
    regardless of their real risk_level. Backfill it to match — final_risk_level
    only diverges once an escalation rule fires, and none exist yet, so at this
    point in history the two are always the same value."""
    RiskAssessment = apps.get_model('monitoring', 'RiskAssessment')
    RiskAssessment.objects.update(final_risk_level=models.F('risk_level'))


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_remove_riskassessment_engine_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='bp_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='final_risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='glucose_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='heart_rate_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='hemoglobin_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='temperature_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RunPython(_copy_risk_level_to_final, migrations.RunPython.noop),
    ]
