# Generated by Django 6.0.8 on 2026-09-05 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_riskassessment_final_risk_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='acknowledged_by',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='findings',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('confirmed', 'Confirmed'), ('corrected', 'Corrected')], db_index=True, default='unreviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
