# Generated by Django 6.0.8 on 2026-09-06 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_riskassessment_bp_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalreading',
            name='source',
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='The staff member whose session submitted this reading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
