# Generated by Django 6.0.8 on 2026-08-16 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('organization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization', 'is_active'], name='locations_l_organiz_bd40e7_idx'),
        ),
    ]
