# Generated by Django 6.0.8 on 2026-09-23 07:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_backfill_main_branch'),
        ('organization', '0019_auditlog_row_level_security'),
        ('patients', '0016_join_request_withdrawn_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='color must be a hex code like #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_tags', to='locations.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_tags', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Clinical Tag',
                'verbose_name_plural': 'Clinical Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)])),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_sessions_added', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to='patients.patient')),
                ('pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to='patients.pregnancy')),
            ],
            options={
                'verbose_name': 'Monitoring Session',
                'verbose_name_plural': 'Monitoring Sessions',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_voicemail', models.BooleanField(default=False)),
                ('two_way_communication', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_notes_added', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_notes', to='patients.patient')),
                ('pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_notes', to='patients.pregnancy')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='clinical_notes.clinicaltag')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='clinical_notes.monitoringsession')),
            ],
            options={
                'verbose_name': 'Monitoring Note',
                'verbose_name_plural': 'Monitoring Notes',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicaltag',
            index=models.Index(fields=['organization', 'name'], name='clinical_no_organiz_dcb2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaltag',
            index=models.Index(fields=['location', 'name'], name='clinical_no_locatio_9d55f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicaltag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('location__isnull', True), ('organization__isnull', False)), models.Q(('location__isnull', False), ('organization__isnull', True)), _connector='OR'), name='clinicaltag_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='clinicaltag',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'name'), name='unique_org_clinical_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='clinicaltag',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location', 'name'), name='unique_location_clinical_tag_name'),
        ),
        migrations.AddIndex(
            model_name='monitoringsession',
            index=models.Index(fields=['patient', 'recorded_at'], name='clinical_no_patient_071dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringsession',
            index=models.Index(fields=['pregnancy', 'recorded_at'], name='clinical_no_pregnan_62dc2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoringsession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0), ('duration_seconds__lte', 86400)), name='monitoringsession_duration_range'),
        ),
        migrations.AddIndex(
            model_name='monitoringnote',
            index=models.Index(fields=['patient', 'recorded_at'], name='clinical_no_patient_359229_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringnote',
            index=models.Index(fields=['pregnancy', 'recorded_at'], name='clinical_no_pregnan_03aff6_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoringnote',
            constraint=models.CheckConstraint(condition=models.Q(('left_voicemail', True), ('two_way_communication', True), _negated=True), name='monitoringnote_not_both_call_outcomes'),
        ),
    ]
