# Generated by Django 6.0.8 on 2026-08-22 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_add_review_status'),
        ('patients', '0003_patient_clinical_identity_and_pregnancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('serial_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('assigned', 'Assigned'), ('returned', 'Returned'), ('faulty', 'Faulty'), ('lost', 'Lost')], db_index=True, default='in_stock', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('acquisition', models.CharField(blank=True, choices=[('sold', 'Sold'), ('loaned', 'Loaned by the hospital'), ('subsidised', 'Subsidised')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='patients.pregnancy')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organization.organization')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_type', models.CharField(choices=[('blood_pressure', 'Blood pressure'), ('heart_rate', 'Heart rate'), ('temperature', 'Temperature')], db_index=True, max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value_secondary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, verbose_name='recorded at')),
                ('source', models.CharField(choices=[('device', 'Wearable device'), ('manual', 'Entered by staff'), ('simulated', 'Simulated')], db_index=True, default='device', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='monitoring.device')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='patients.pregnancy')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='The staff member who entered this, for manual readings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'status'], name='monitoring__organiz_6ff00b_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'assigned')), fields=('assigned_pregnancy',), name='one_active_device_per_pregnancy'),
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['pregnancy', 'reading_type', '-recorded_at'], name='monitoring__pregnan_8d0a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['pregnancy', '-recorded_at'], name='monitoring__pregnan_053400_idx'),
        ),
        migrations.AddConstraint(
            model_name='vitalreading',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='reading_value_positive'),
        ),
    ]
