# Generated by Django 6.0.8 on 2026-09-24 09:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0001_initial'),
        ('locations', '0004_backfill_main_branch'),
        ('organization', '0022_notification_row_level_security'),
        ('patients', '0016_join_request_withdrawn_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='color must be a hex code like #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_statuses_added', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='patients.patient')),
                ('pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='patients.pregnancy')),
            ],
            options={
                'verbose_name': 'Patient Status',
                'verbose_name_plural': 'Patient Statuses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='clinical_no_patient_a418f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='color must be a hex code like #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_labels', to='locations.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_labels', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Status Label',
                'verbose_name_plural': 'Status Labels',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'name'], name='clinical_no_organiz_7dc4a3_idx'), models.Index(fields=['location', 'name'], name='clinical_no_locatio_330093_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('location__isnull', True), ('organization__isnull', False)), models.Q(('location__isnull', False), ('organization__isnull', True)), _connector='OR'), name='statuslabel_exactly_one_scope'), models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'name'), name='unique_org_status_label_name'), models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location', 'name'), name='unique_location_status_label_name')],
            },
        ),
    ]
