# Generated by Django 6.0.8 on 2026-08-22 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_devices_and_vital_readings'),
        ('patients', '0003_patient_clinical_identity_and_pregnancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('stable', 'Stable'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('findings', models.JSONField(default=list, help_text='Why this level was reached, each tied to the reading that caused it.')),
                ('source', models.CharField(choices=[('rules', 'Clinical rules'), ('model', 'AI model')], db_index=True, default='rules', max_length=20)),
                ('engine_version', models.CharField(help_text='Which rules or model version produced this, so a judgement can be traced back.', max_length=40)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('previous_level', models.CharField(blank=True, choices=[('stable', 'Stable'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_assessments', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments', to='patients.pregnancy')),
            ],
            options={
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['pregnancy', '-assessed_at'], name='monitoring__pregnan_a52305_idx'), models.Index(fields=['level', '-assessed_at'], name='monitoring__level_e55b6a_idx')],
            },
        ),
    ]
