# Generated by Django 6.0.8 on 2026-09-25 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0002_statuslabel_patientstatus'),
        ('locations', '0004_backfill_main_branch'),
        ('organization', '0023_status_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_templates', to='locations.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_templates', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note Template',
                'verbose_name_plural': 'Note Templates',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['organization', 'title'], name='clinical_no_organiz_550a49_idx'), models.Index(fields=['location', 'title'], name='clinical_no_locatio_8bb8b1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('location__isnull', True), ('organization__isnull', False)), models.Q(('location__isnull', False), ('organization__isnull', True)), _connector='OR'), name='notetemplate_exactly_one_scope'), models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'title'), name='unique_org_note_template_title'), models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location', 'title'), name='unique_location_note_template_title')],
            },
        ),
    ]
