# Generated by Django 6.0.8 on 2026-09-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_risk_assessment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vitalreading',
            name='reading_value_positive',
        ),
        migrations.RemoveIndex(
            model_name='vitalreading',
            name='monitoring__pregnan_8d0a6d_idx',
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='body_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='diastolic_bp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='heart_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='phys_activity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='stress_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='systolic_bp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.RemoveField(
            model_name='vitalreading',
            name='reading_type',
        ),
        migrations.RemoveField(
            model_name='vitalreading',
            name='value',
        ),
        migrations.RemoveField(
            model_name='vitalreading',
            name='value_secondary',
        ),
    ]
