# Generated by Django 6.0.8 on 2026-09-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_risk_level_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=20),
        ),
    ]
