# Generated by Django 6.0.8 on 2026-09-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_riskassessment_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='engine_version',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='score',
        ),
    ]
