# Generated by Django 6.0.8 on 2026-09-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_remove_riskassessment_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='bp_category',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='glucose_category',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='heart_rate_category',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='hemoglobin_category',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='source',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='temperature_category',
        ),
    ]
