# Generated by Django 6.0.8 on 2026-09-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_remove_riskassessment_bp_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='bp_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='glucose_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='heart_rate_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='hemoglobin_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='temperature_category',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
