# Generated by Django 6.0.8 on 2026-09-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_remove_vitalreading_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='doctor_notified',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
