"""Request validation and the one aggregate response shape for a care plan.

``plan_payload`` is the single place a plan is turned into JSON, for staff and
for the patient alike, so the two screens can never disagree about what a plan
contains. A patient gets the same four sections read-only; the only things
withheld from her are staff bookkeeping (who reviewed it, inputs, row ids).
"""

from __future__ import annotations

from datetime import timedelta

from django.utils import timezone
from rest_framework import serializers

from momcare_platform.core.common.obstetrics import calculate_gestational_age as _gestational_age
from momcare_platform.core.common.obstetrics import trimester_for
from momcare_platform.core.patients.models import DIETARY_PREFERENCE_CHOICES, Pregnancy

from .. import services
from ..guardrails import CONTACT_MESSAGE, DISCLAIMER, WARNING_SIGNS
from ..models import SECTION_EXERCISE, SECTION_NUTRITION, CarePlan, HospitalPreference

# Shown to staff only: the generator's rules and the vital/trimester cut-offs
# have not been reviewed by an obstetrician or dietitian. See the design doc.
CLINICAL_REVIEW_STATUS = "unreviewed"

# Shown when the live search found no official guidance: the plan is the AI's own work.
_AI_NOTICE = (
    "No official guideline for your country was found for this plan. It was generated by AI. "
    "Please follow what your care team tells you."
)

_FACTOR_LABELS = {
    "previous_c_section": "Previous C-section",
    "previous_preeclampsia": "Previous pre-eclampsia",
    "previous_gestational_diabetes": "Previous gestational diabetes",
    "previous_preterm_birth": "Previous preterm birth",
    "chronic_hypertension": "Chronic hypertension",
    "diabetes": "Diabetes",
    "multiple_pregnancy": "Multiple pregnancy",
}


def _name(user) -> str | None:
    if user is None:
        return None
    return user.get_full_name() or user.email


def _week_label(plan: CarePlan) -> str:
    day_one = plan.period_start - timedelta(days=(plan.month_number - 1) * 30)
    first = (plan.period_start - day_one).days // 7
    last = (plan.period_end - day_one).days // 7
    return f"weeks {first}-{last}"


def _section(plan: CarePlan, section: str) -> dict:
    layered = services.layered_section(plan, section)
    reviewed = plan.status in (CarePlan.STATUS_REVIEWED, CarePlan.STATUS_FINALIZED)
    week = _current_week(plan)
    return {
        # How she is doing in THIS section's own vitals (nutrition: hemoglobin, glucose, blood
        # pressure; exercise: heart rate, activity, stress, blood pressure). Computed by code.
        "progress": (week.progress or {}).get(section) if week else None,
        "label": "reviewed_by_provider" if reviewed else "suggested_automatically",
        "content": layered["content"],
        # Where the advice comes from, always shown. ``basis`` says how:
        #   web_search -- the AI searched the web for the patient's country's official
        #     guidance for THIS plan; ``source_links`` are the pages it really read
        #     (title, url, host), recorded by code from the search, not typed by the model;
        #   ai_only    -- no official document was found: the plan is the AI's own work
        #     and ``generated_by_ai_notice`` says so (show it);
        #   baseline   -- MomCare's fixed generic plan (the model failed).
        # The content itself is never checked against the pages, hence sources_verified false.
        "basis": layered["basis"],
        "sources": layered["sources"],
        "source_links": layered["source_links"],
        "generated_by_ai_notice": _AI_NOTICE if layered["basis"] == "ai_only" else None,
        "sources_verified": False,
        # When this version was created (staff edits to it are separate and keep
        # their own item-level `source: "staff"` tag).
        "generated_at": layered["generated_at"],
        "based_on_reading_at": layered["based_on_reading_at"],
        "is_fallback": layered["is_fallback"],
    }


def _current_week(plan: CarePlan):
    """The plan's newest week -- for the current plan, the week she is in."""
    return plan.weeks.order_by("-week_number").first()


def _advice_payload(week) -> dict | None:
    """The newest quick advice for the week -- but only while it is newer than the
    weekly plan: once the week has been re-planned, the plan already answers the
    condition the advice was written for."""
    advice = week.advice.select_related("reading").order_by("-created_at").first() if week else None
    if advice is None:
        return None
    newest_version = week.versions.order_by("-created_at").first()
    if newest_version is not None and advice.created_at < newest_version.created_at:
        return None
    content = advice.content
    return {
        "created_at": advice.created_at,
        "for_reading_at": advice.reading.recorded_at if advice.reading else None,
        "risk_level": advice.risk_level,
        "tips": content["tips"],
        "contact_care_team": content["contact_care_team"],
        # Set by code for high risk -- never left to the model.
        "contact_message": CONTACT_MESSAGE if content["contact_care_team"] else None,
        "basis": content.get("basis", "ai_only"),
        "sources": content["sources"],
        "source_links": content.get("source_links", []),
        "generated_by_ai_notice": _AI_NOTICE if content.get("basis", "ai_only") == "ai_only" else None,
        "sources_verified": False,
        "is_fallback": advice.is_fallback,
    }


def _contact_payload(plan: CarePlan, pregnancy, today) -> dict:
    """Set by code, never by the model: while her latest reading is high risk the plan
    carries "contact your care team", whether or not a new quick tip was written."""
    current = plan.period_start <= today <= plan.period_end
    high = current and services.latest_risk_level(pregnancy) == "high"
    return {"contact_care_team": high, "contact_message": CONTACT_MESSAGE if high else None}


def _week_payload(week) -> dict | None:
    if week is None:
        return None
    return {
        "week_number": week.week_number,
        "week_start": week.week_start,
        "week_end": week.week_end,
        "replans": week.replans,
        "last_replan_reason": week.last_replan_reason,
    }


def section_payload(plan: CarePlan, section: str, *, for_patient: bool = False) -> dict:
    """One section on its own -- nutrition and exercise are separate responses as
    well as separate parts of the aggregate."""
    payload = {
        "care_plan_id": str(plan.id),
        "month_number": plan.month_number,
        "period_start": plan.period_start,
        "period_end": plan.period_end,
        "weeks_label": _week_label(plan),
        "week": _week_payload(_current_week(plan)),
        "status": plan.status,
        "section": section,
        **_section(plan, section),
        "disclaimer": DISCLAIMER,
        "warning_signs": WARNING_SIGNS,
    }
    if not for_patient:
        payload["clinical_review"] = CLINICAL_REVIEW_STATUS
    return payload


def plan_payload(plan: CarePlan, *, for_patient: bool = False) -> dict:
    pregnancy = plan.pregnancy
    patient = pregnancy.patient
    today = timezone.localdate()
    state = plan.current_state or {}
    trimester = state.get("trimester")
    if trimester is None:
        trimester = trimester_for(_gestational_age(pregnancy.edd, plan.period_start))

    week = _current_week(plan)
    medications = plan.medications.filter(is_active=True)
    notes = plan.notes.filter(is_active=True)
    payload = {
        "id": str(plan.id),
        "pregnancy_id": str(plan.pregnancy_id),
        "month_number": plan.month_number,
        "period_start": plan.period_start,
        "period_end": plan.period_end,
        "weeks_label": _week_label(plan),
        "trimester": trimester,
        "status": plan.status,
        "is_current_month": plan.period_start <= today <= plan.period_end,
        "message": (
            f"This is your plan for week {week.week_number}. Keep following it; we will tell you if anything needs "
            "to change."
            if week
            else None
        ),
        "week": _week_payload(week),
        "progress": week.progress if week and week.progress else None,
        "reading_advice": _advice_payload(week),
        **_contact_payload(plan, pregnancy, today),
        "weeks": [
            {
                "week_number": w.week_number,
                "week_start": w.week_start,
                "week_end": w.week_end,
                "trend": ((w.progress or {}).get("facts") or {}).get("trend", {})
                and w.progress["facts"]["trend"]["direction"],
                "replans": w.replans,
            }
            for w in plan.weeks.order_by("-week_number")
        ],
        "nutrition": _section(plan, SECTION_NUTRITION),
        "exercise": _section(plan, SECTION_EXERCISE),
        "medications": [
            {"id": str(m.id), "text": m.text, "added_by": _name(m.added_by), "created_at": m.created_at}
            for m in medications
        ],
        "notes": [
            {"id": str(n.id), "text": n.text, "added_by": _name(n.added_by), "created_at": n.created_at} for n in notes
        ],
        "allergies_and_conditions": {
            "food_allergies": patient.food_allergies or [],
            "dietary_preference": patient.dietary_preference,
            "conditions": [
                {"field": f, "label": _FACTOR_LABELS[f]}
                for f in Pregnancy.FACTOR_FIELDS
                if getattr(pregnancy, f) == Pregnancy.YES
            ],
        },
        "disclaimer": DISCLAIMER,
        "warning_signs": WARNING_SIGNS,
    }
    if not for_patient:
        payload.update(
            {
                "reviewed_by": _name(plan.reviewed_by),
                "reviewed_at": plan.reviewed_at,
                "finalized_by": _name(plan.finalized_by),
                "finalized_at": plan.finalized_at,
                "last_evaluated_at": plan.last_evaluated_at,
                "clinical_review": CLINICAL_REVIEW_STATUS,
            }
        )
    return payload


def preference_payload(pref: HospitalPreference) -> dict:
    return {
        "id": str(pref.id),
        "region": pref.region,
        "trimester": pref.trimester,
        "section": pref.section,
        "item_key": pref.item_key,
        "status": pref.status,
        "guidance": pref.payload.get("guidance", ""),
        "replacements": pref.payload.get("replacements", []),
        "supporting_staff": pref.supporting_staff,
        "decided_by": _name(pref.decided_by),
        "decided_at": pref.decided_at,
        "created_at": pref.created_at,
    }


# -- input -------------------------------------------------------------------


class AdjustmentCreateSerializer(serializers.Serializer):
    section = serializers.ChoiceField(choices=[SECTION_NUTRITION, SECTION_EXERCISE])
    list_name = serializers.CharField(max_length=40)
    action = serializers.ChoiceField(choices=["add", "edit", "remove"])
    item_key = serializers.CharField(max_length=80, required=False, allow_blank=True, default="")
    content = serializers.DictField(required=False, default=dict)


class AdjustmentUpdateSerializer(serializers.Serializer):
    content = serializers.DictField()


class TextSerializer(serializers.Serializer):
    text = serializers.CharField(max_length=2000, trim_whitespace=True)


class ReasonSerializer(serializers.Serializer):
    reason = serializers.CharField(max_length=500, required=False, allow_blank=True, default="")


class AllergiesConditionsSerializer(serializers.Serializer):
    food_allergies = serializers.ListField(child=serializers.CharField(max_length=60), required=False, max_length=30)
    dietary_preference = serializers.ChoiceField(choices=[c[0] for c in DIETARY_PREFERENCE_CHOICES], required=False)

    def get_fields(self):
        fields = super().get_fields()
        for factor in Pregnancy.FACTOR_FIELDS:
            fields[factor] = serializers.ChoiceField(choices=["yes", "no", "unknown"], required=False)
        return fields

    def validate(self, attrs):
        if not attrs:
            raise serializers.ValidationError("Send at least one field to change.")
        return attrs


class GuidanceSerializer(serializers.Serializer):
    guidance = serializers.CharField(max_length=1000)


class OptionalGuidanceSerializer(serializers.Serializer):
    guidance = serializers.CharField(max_length=1000, required=False)
