# Generated by Django 6.0.8 on 2026-10-04 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0016_rename_review_status_values'),
        ('organization', '0031_ai_summary_template_row_level_security'),
        ('patients', '0019_patient_dietary_preference_patient_food_allergies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_number', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('reviewed', 'Reviewed'), ('finalized', 'Finalized')], db_index=True, default='in_progress', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('current_state', models.JSONField(blank=True, default=dict)),
                ('current_state_key', models.CharField(blank=True, max_length=64)),
                ('loosen_candidate_key', models.CharField(blank=True, max_length=64)),
                ('loosen_candidate_count', models.PositiveSmallIntegerField(default=0)),
                ('last_outcome', models.CharField(blank=True, max_length=12)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plans', to='patients.pregnancy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_number'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('section', models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise')], max_length=20)),
                ('item_key', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit'), ('remove', 'Remove')], max_length=10)),
                ('list_name', models.CharField(max_length=40)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='care_plans.careplan')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='care_plans.careplan')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='care_plans.careplan')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanSectionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise')], max_length=20)),
                ('content', models.JSONField()),
                ('inputs', models.JSONField(default=dict)),
                ('state_key', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='care_plans.careplan')),
                ('source_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.vitalreading')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('trimester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('section', models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise')], max_length=20)),
                ('item_key', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], db_index=True, default='suggested', max_length=12)),
                ('payload', models.JSONField(default=dict)),
                ('supporting_staff', models.PositiveSmallIntegerField(default=0)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('trimester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('section', models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise')], max_length=20)),
                ('item_key', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('replace', 'Replace'), ('remove', 'Remove'), ('add', 'Add')], max_length=10)),
                ('original', models.JSONField(blank=True, default=dict)),
                ('replacement', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='care_plans.careplan')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patient')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.pregnancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='careplan',
            constraint=models.UniqueConstraint(fields=('pregnancy', 'month_number'), name='uniq_careplan_pregnancy_month'),
        ),
        migrations.AddIndex(
            model_name='careplanadjustment',
            index=models.Index(fields=['care_plan', 'section', 'is_active'], name='care_plans__care_pl_41d2be_idx'),
        ),
        migrations.AddIndex(
            model_name='careplansectionversion',
            index=models.Index(fields=['care_plan', 'section', '-created_at'], name='care_plans__care_pl_6f46d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitalpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['suggested', 'approved'])), fields=('organization', 'region', 'trimester', 'section', 'item_key'), name='uniq_open_hospital_preference'),
        ),
        migrations.AddIndex(
            model_name='plancorrection',
            index=models.Index(fields=['organization', 'region', 'trimester', 'section', 'item_key'], name='care_plans__organiz_3fdf7c_idx'),
        ),
    ]
