# Generated by Django 6.0.8 on 2026-10-06 04:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_plans', '0001_initial'),
        ('monitoring', '0016_rename_review_status_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplan',
            name='loosen_candidate_count',
        ),
        migrations.RemoveField(
            model_name='careplan',
            name='loosen_candidate_key',
        ),
        migrations.CreateModel(
            name='CareWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('baseline_state', models.JSONField(blank=True, default=dict)),
                ('baseline_state_key', models.CharField(blank=True, max_length=64)),
                ('worse_since', models.DateTimeField(blank=True, null=True)),
                ('worse_readings', models.PositiveSmallIntegerField(default=0)),
                ('last_advice_state_key', models.CharField(blank=True, max_length=64)),
                ('replans', models.PositiveSmallIntegerField(default=0)),
                ('last_replan_reason', models.CharField(blank=True, max_length=200)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='care_plans.careplan')),
            ],
            options={
                'ordering': ['-week_number'],
            },
        ),
        migrations.AddField(
            model_name='careplansectionversion',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='care_plans.careweek'),
        ),
        migrations.CreateModel(
            name='ReadingAdvice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(max_length=20)),
                ('state_key', models.CharField(max_length=64)),
                ('content', models.JSONField()),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='care_plans.careplan')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.vitalreading')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='care_plans.careweek')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='careweek',
            constraint=models.UniqueConstraint(fields=('care_plan', 'week_number'), name='uniq_careweek_plan_week'),
        ),
        migrations.AddIndex(
            model_name='readingadvice',
            index=models.Index(fields=['care_plan', '-created_at'], name='care_plans__care_pl_ef3b53_idx'),
        ),
    ]
