# Generated by Django 6.0.8 on 2026-08-21 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_locations_l_organiz_bd40e7_idx'),
        ('patients', '0002_initial'),
        ('staff', '0003_add_staff_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version', models.CharField(default='v1.0', help_text='Which consent policy the patient agreed to.', max_length=20)),
                ('method', models.CharField(choices=[('in_person', 'In person, signed'), ('verbal', 'Verbal, witnessed'), ('digital', 'Digital')], default='in_person', max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'consents',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lmp', models.DateField(blank=True, help_text='First day of the last period. May be unknown or unreliable.', null=True, verbose_name='last menstrual period')),
                ('edd', models.DateField(blank=True, help_text='Defaults to LMP + 280 days; override when ultrasound dating differs.', null=True, verbose_name='estimated delivery date')),
                ('edd_source', models.CharField(choices=[('lmp', 'Last menstrual period'), ('ultrasound', 'Ultrasound dating'), ('clinical', 'Clinical assessment')], default='lmp', max_length=20)),
                ('edd_confirmed_at', models.DateTimeField(blank=True, help_text='When the dating was last confirmed or corrected.', null=True)),
                ('gravida', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('para', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('delivered', 'Delivered'), ('miscarriage', 'Miscarriage'), ('termination', 'Termination'), ('stillbirth', 'Stillbirth'), ('ended_other', 'Ended — other')], db_index=True, default='active', max_length=20)),
                ('outcome_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'pregnancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyRiskFactors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_c_section', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('previous_preeclampsia', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('previous_gestational_diabetes', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('previous_preterm_birth', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('chronic_hypertension', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('diabetes', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('multiple_pregnancy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
            ],
            options={
                'verbose_name': 'pregnancy risk factors',
                'verbose_name_plural': 'pregnancy risk factors',
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consent_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A−'), ('B+', 'B+'), ('B-', 'B−'), ('AB+', 'AB+'), ('AB-', 'AB−'), ('O+', 'O+'), ('O-', 'O−')], max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='cnic',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='CNIC'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Mobile app account, if she has one. A patient can exist without it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['cnic'], name='patients_pa_cnic_6072c8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consent',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_pregnancies', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='pregnancyriskfactors',
            name='pregnancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='patients.pregnancy'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['patient', '-recorded_at'], name='patients_co_patient_7a2a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['patient', 'status'], name='patients_pr_patient_03e259_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['edd'], name='patients_pr_edd_70f5a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='pregnancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('patient',), name='one_active_pregnancy_per_patient'),
        ),
    ]
