# Generated by Django 6.0.8 on 2026-08-28 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_clinical_identity_and_pregnancy'),
        ('staff', '0003_add_staff_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='staff.staff')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='patients.pregnancy')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pregnancy', '-created_at'], name='patients_cl_pregnan_3ca866_idx')],
            },
        ),
    ]
