# Generated by Django 6.0.8 on 2026-09-01 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_clinicalnote'),
        ('staff', '0003_add_staff_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('nurse', 'Nurse'), ('provider', 'Provider'), ('care_manager', 'Care manager')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who made this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_team_memberships', to='patients.pregnancy')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_team_memberships', to='staff.staff')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['pregnancy', 'role', 'is_active'], name='patients_ca_pregnan_f6160f_idx'), models.Index(fields=['staff', 'role', 'is_active'], name='patients_ca_staff_i_7ef0db_idx')],
            },
        ),
    ]
