# Generated by Django 6.0.8 on 2026-09-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_delete_clinicalnote'),
        ('staff', '0007_secondary_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='secondary_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='staff.secondaryprovider'),
        ),
    ]
