# Generated by Django 6.0.8 on 2026-09-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_patient_join_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20),
        ),
    ]
