# Generated by Django 6.0.8 on 2026-09-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_join_request_withdrawn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_monitoring_contact_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_reading_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
