# Generated by Django 6.0.8 on 2026-10-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'No preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('other', 'Other')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_allergies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
