# Generated by Django 6.0.8 on 2026-10-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_backfill_main_branch'),
        ('patients', '0021_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientjoinrequest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='locations.location'),
        ),
    ]
