# Generated by Django 6.0.8 on 2026-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_add_staff_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='staff/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='practicing_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualifications',
            field=models.CharField(blank=True, help_text='e.g. MBBS, FCPS (Gynae & Obs)', max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='registration_authority',
            field=models.CharField(blank=True, help_text='e.g. PMDC, Pakistan Nursing Council', max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialty',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
