# Generated by Django 6.0.8 on 2026-09-05 07:45

import momcare_platform.core.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_photo_staff_practicing_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.FileField(blank=True, null=True, storage=momcare_platform.core.common.storage.DatabaseStorage(), upload_to='staff/%Y/%m/'),
        ),
    ]
