# Generated by Django 6.0.8 on 2026-09-13 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_alter_staff_photo"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="staffinvite",
            name="staff_staff_organiz_5f7c90_idx",
        ),
        migrations.RemoveConstraint(
            model_name="staffinvite",
            name="unique_pending_invite_per_org_email",
        ),
        migrations.DeleteModel(
            name="StaffInvite",
        ),
    ]
