# Generated by Django 6.0.8 on 2026-09-15 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_program_enrollment_row_level_security'),
        ('staff', '0006_remove_staff_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('affiliation', models.CharField(blank=True, help_text="Where they practise — e.g. 'Rural Health Centre, Kahuta'.", max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_providers', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Secondary Provider',
                'verbose_name_plural': 'Secondary Providers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'name'], name='staff_secon_organiz_27d9f0_idx')],
            },
        ),
    ]
