# Generated by Django 6.0.8 on 2026-08-22 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0002_risk_assessment'),
        ('patients', '0003_patient_clinical_identity_and_pregnancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('tier', models.PositiveSmallIntegerField(default=1, help_text='How far up the ladder this alert has climbed.')),
                ('raised_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('recovered', 'Readings returned to range'), ('handled', 'Handled by a clinician'), ('pregnancy_ended', 'Pregnancy ended')], max_length=30)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='monitoring.riskassessment')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.pregnancy')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('raised', 'Raised'), ('worsened', 'Worsened'), ('escalated', 'Escalated'), ('notified', 'Notified'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], max_length=20)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alert')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-raised_at'], name='alerts_aler_status_e82dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['pregnancy', 'status'], name='alerts_aler_pregnan_8793d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'acknowledged'))), fields=('pregnancy',), name='one_live_alert_per_pregnancy'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['alert', 'created_at'], name='alerts_aler_alert_i_4f41be_idx'),
        ),
    ]
